### ISSUE TITLE
OpenMx

### ISSUE THREAD

**Issue by sjbonner** [jackthomas818/simtrapoccR#5]
The package requires the OpenMx package just to access the omxMnor() function for computing the area under the bivariate normal density. The mvtnorm package is much smaller and has a function, pmvnorm(), that does the same thing. The [open](https://github.com/jackthomas818/simtrapoccR/tree/OpenMx-free) branch makes the switch and removes the dependence on OpenMx.

@jackthomas818 can you confirm this is correct and then merge the branch if it makes sense?

**Comment by jackthomas818** [comment]
Closed by #6
